package org.jlab.mya;

/**
 *
 * @author ryans
 */
public enum EventCode {
    UPDATE, // 0
    NETWORK_DISCONNECTION, // 1
    ARCHIVING_OF_CHANNEL_TURNED_OFF, // 2
    ARCHIVER_SHUTDOWN, // 3
    UNKNOWN_UNAVAILABILTY, // 4
    NOT_USED_5,
    NOT_USED_6,
    NOT_USED_7,
    NOT_USED_8,
    NOT_USED_9,
    NOT_USED_10,
    NOT_USED_11,
    NOT_USED_12,
    NOT_USED_13,
    NOT_USED_14,
    NOT_USED_15,
    ORIGIN_OF_CHANNELS_HISTORY, // 16
    NOT_USED_17,
    NOT_USED_18,
    NOT_USED_19,
    NOT_USED_20,
    NOT_USED_21,
    NOT_USED_22,
    NOT_USED_23,
    NOT_USED_24,
    NOT_USED_25,
    NOT_USED_26,
    NOT_USED_27,
    NOT_USED_28,
    NOT_USED_29,
    NOT_USED_30,
    NOT_USED_31,
    NOT_USED_32,
    NOT_USED_33,
    NOT_USED_34,
    NOT_USED_35,
    NOT_USED_36,
    NOT_USED_37,
    NOT_USED_38,
    NOT_USED_39,
    NOT_USED_40,
    NOT_USED_41,
    NOT_USED_42,
    NOT_USED_43,
    NOT_USED_44,
    NOT_USED_45,
    NOT_USED_46,
    NOT_USED_47,
    CHANNELS_PRIOR_DATA_DISCARDED // 48    
}
