services:
  mya:
    extends:
      file: ../compose.yaml
      service: mya

  dev:
    image: jeffersonlab/java-devcontainer:1.0.2
    hostname: dev
    container_name: dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock