name: Publish to Maven Central

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: temurin
    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
    - name: Publish
      run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
      env:
        ORG_GRADLE_PROJECT_sonatypeUsername : ${{ secrets.OSSRH_USERNAME }}
        ORG_GRADLE_PROJECT_sonatypePassword : ${{ secrets.OSSRH_PASSWORD }}
        ORG_GRADLE_PROJECT_signingKey : ${{ secrets.SIGNING_KEY }}
        ORG_GRADLE_PROJECT_signingPassword : ${{ secrets.SIGNING_PASSWORD }}