name: Publish to Maven Central

on:
  release:
    types: [published]
  workflow_dispatch:
  workflow_call:
    inputs:
      semvertag:
        required: true
        type: string
    secrets:
      OSSRH_USERNAME:
        required: true
      OSSRH_PASSWORD:
        required: true
      SIGNING_KEY:
        required: true
      SIGNING_PASSWORD:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: temurin
    - uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: wrapper
    - name: Publish
      run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
      env:
        ORG_GRADLE_PROJECT_sonatypeUsername : ${{ secrets.OSSRH_USERNAME }}
        ORG_GRADLE_PROJECT_sonatypePassword : ${{ secrets.OSSRH_PASSWORD }}
        ORG_GRADLE_PROJECT_signingKey : ${{ secrets.SIGNING_KEY }}
        ORG_GRADLE_PROJECT_signingPassword : ${{ secrets.SIGNING_PASSWORD }}