name: Release

on:
  push:
    paths:
      - 'VERSION'

jobs:
  release:
    uses: jeffersonlab/java-workflows/.github/workflows/release.yml@main

  maven_publish:
    needs:
      - release
    uses: jeffersonlab/java-workflows/.github/workflows/maven-publish.yml@main
    secrets: inherit

  docs_publish:
    needs:
      - release
    uses: jeffersonlab/java-workflows/.github/workflows/gh-pages-publish.yml@main
    with:
      semvertag: ${{ needs.release.outputs.semvertag }}
    secrets: inherit